objects/EMember__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>EMember</label>
    <nameField>
        <displayFormat>Mid-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>Eid-{0000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contributed_Amount__c</fullName>
        <label>Contributed Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EMember__c</fullName>
        <label>EMember</label>
        <referenceTo>EMember__c</referenceTo>
        <relationshipLabel>ExpenseMembers</relationshipLabel>
        <relationshipName>ExpenseMembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>ExpenseMembers</relationshipLabel>
        <relationshipName>ExpenseMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Member</label>
    <nameField>
        <displayFormat>Emid-{0000}</displayFormat>
        <label>Expense Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExpenseMembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ExtnExpense.cls
public with sharing class ExtnExpense
{
    public list<Expense_Member__c> l {get;set;}
    public Expense__c expObj{get;set;}
    public ExtnExpense(ApexPages.StandardController controller) 
    {
        expObj = (Expense__c)controller.getRecord();
        l = new list<Expense_Member__c>();
    }
    
    public void getExpenseMembers()
    {
        l =  [Select Name, Expense__c, EMember__r.First_Name__c,EMember__r.Last_Name__c, Contributed_Amount__c from Expense_Member__c where Expense__c =: expObj.Id];
        
    }
}