objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>Eid-{0000}</displayFormat>
        <label>Expense Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseEXT_Test.cls
@isTest
public class ExpenseEXT_Test
{
    public static testMethod void myTest()
    {
     Expense__c exp = new Expense__c();
        exp.Event__c='abc';
        exp.Amount__c=1000;
        exp.Date__c=date.parse('12/27/2015');
        insert exp;
       
        
        ExtnExpense expExt = new ExtnExpense(new ApexPages.StandardController(exp));
       
        expExt.getExpenseMembers();
        
        
    }

    
}